POST http://localhost:5000/api/products
Content-Type: application/json

  {
    "title": "Lenovo X1",
    "description": "Lightweight business laptop with a 14-inch display, 16GB RAM, and 512GB SSD.",
    "category": "laptop",
    "price": 1200,
    "amount": 15,
    "discount": 10
  }